<a href="https://colab.research.google.com/github/meganandakai-ship-it/Kelambatan-daop-1-Jakarta/blob/main/Membuat_Gabungan_data_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# 2. Path folder tempat file berada
import os
folder_path = "/content/drive/MyDrive/Rekap gangguan"

# Cek apakah folder ada
if os.path.exists(folder_path):
    print("Status: Folder ditemukan ✔️")
else:
    print("Status: Folder TIDAK ditemukan ❌ — periksa penamaan folder")
    raise SystemExit()

Status: Folder ditemukan ✔️

In [ ]:
import os
import pandas as pd

# 1. Path folder tempat file berada
folder_path = "/content/drive/MyDrive/Rekap gangguan"

# 2. Cek apakah folder ada
if os.path.exists(folder_path):
    print("Status: Folder ditemukan ✔️")
else:
    raise SystemExit("Status: Folder TIDAK ditemukan ❌ - periksa penamaan folder")

# 3. Ambil semua file CSV dalam folder
files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]
print(f"Jumlah file ditemukan: {len(files)}")

# 4. List untuk menampung dataframe
df_list = []

for file in files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)

    # Hapus kolom '#' jika ada
    if '#' in df.columns:
        df = df.drop(columns=['#'])

    df_list.append(df)

# 5. Gabungkan semua dataframe
df_final = pd.concat(df_list, ignore_index=True)

print("Penggabungan selesai ✔️")
print(f"Total baris setelah digabung: {len(df_final)}")

# 6. Simpan file baru
output_path = "/content/drive/MyDrive/Rekap gangguan 2.csv"
df_final.to_csv(output_path, index=False)

print(f"File berhasil disimpan sebagai: {output_path}")

Status: Folder ditemukan ✔️
Jumlah file ditemukan: 161
Penggabungan selesai ✔️
Total baris setelah digabung: 518524
File berhasil disimpan sebagai: /content/drive/MyDrive/Rekap gangguan 2.csv

In [ ]:
import pandas as pd

# 1. Baca file Rekap gangguan 2
path_input = "/content/drive/MyDrive/Rekap gangguan 2.csv"
df = pd.read_csv(path_input)

# 2. Ubah kolom Tgl KA menjadi datetime (format hari-bulan-tahun)
df['Tgl KA'] = pd.to_datetime(df['Tgl KA'], dayfirst=True, errors='coerce')

# 3. Buat batas tanggal: 1 Februari 2025 s.d. 31 Oktober 2025
start_date = pd.to_datetime("01-02-2025", dayfirst=True)
end_date   = pd.to_datetime("31-10-2025", dayfirst=True)

# 4. Filter hanya baris dalam rentang tanggal tersebut
mask = (df['Tgl KA'] >= start_date) & (df['Tgl KA'] <= end_date)
df_filtered = df.loc[mask].copy()

print(f"Jumlah baris setelah difilter: {len(df_filtered)}")

# 5. Simpan sebagai Rekap gangguan 3
path_output = "/content/drive/MyDrive/Rekap gangguan 3.csv"
df_filtered.to_csv(path_output, index=False)

print(f"File berhasil disimpan sebagai: {path_output}")

# 6. Tampilkan 10 contoh data hasil filter
df_filtered.head(10)

/tmp/ipython-input-1740256465.py:8: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['Tgl KA'] = pd.to_datetime(df['Tgl KA'], dayfirst=True, errors='coerce')

Jumlah baris setelah difilter: 187342
File berhasil disimpan sebagai: /content/drive/MyDrive/Rekap gangguan 3.csv

,Tgl KA,No KA,Id Penyebab,Id Akibat,Lokasi,Lokasi.1,Andil,Keterangan,source_file
0,2025-06-24,331,D1110,AT11,Lemahabang,Cikarang,13,imbas gangguan lok ka 2522,NaN
1,2025-06-24,332,D1110,AT11,-,Lemahabang,15,Gangguan lok KA 2522,NaN
8,2025-08-21,28,C3121,AT32,-,Gambir,18,ttunggu rangkaian dari ka 27 dat lambat imbas ...,NaN
9,2025-08-21,116,C3121,AT32,-,Jatinegara,5,antrian ka dengan ka 28 ber lambat imbas tungg...,NaN
10,2025-08-04,166,C1118,AL10,-,Kosambi,54,imbas rel patah w.11b empl kos,NaN
11,2025-08-04,2,C1118,AL10,-,Kosambi,28,imbas rel patah w.11b empl kos,NaN
12,2025-08-04,128,C1118,AL10,-,Kosambi,44,imbas rel patah w.11b empl kos,NaN
13,2025-08-04,16,C1118,AL10,-,Kosambi,41,imbas rel patah w.11b empl kos,NaN
14,2025-08-04,282,C1118,AL10,-,Kosambi,24,imbas rel patah w.11b empl kos,NaN
15,2025-08-04,118,C1118,AL10,-,Kosambi,29,imbas rel patah w.11b empl kos,NaN

In [ ]:
import pandas as pd

# 1. Baca file Rekap gangguan 3
path_rekap = "/content/drive/MyDrive/Rekap gangguan 3.csv"
df = pd.read_csv(path_rekap)

# 2. Baca file List gangguan
#    Sesuaikan nama file & ekstensi (.csv / .xlsx) jika berbeda
path_list = "/content/drive/MyDrive/List gangguan.csv"
list_gangguan = pd.read_csv(path_list)

# Jika file List gangguan berupa Excel, gunakan ini:
# list_gangguan = pd.read_excel(path_list)

# 3. Buat mapping: kodifikasi → Nama Penyebab
mapping = list_gangguan.set_index("Kodifikasi")["Nama Penyebab"]

# 4. Tambahkan kolom baru Nama_Penyebab berdasarkan Id Penyebab
df["Nama_Penyebab"] = df["Id Penyebab"].map(mapping)

# 5. Posisikan kolom Nama_Penyebab di sebelah kanan Id Penyebab
cols = list(df.columns)
idx = cols.index("Id Penyebab")
# pindahkan kolom Nama_Penyebab ke posisi setelah Id Penyebab
cols.insert(idx + 1, cols.pop(cols.index("Nama_Penyebab")))
df = df[cols]

# 6. Simpan sebagai file baru
output_path = "/content/drive/MyDrive/Rekap gangguan 4.csv"
df.to_csv(output_path, index=False)

print("Proses selesai ✔️")
print(f"File disimpan sebagai: {output_path}")
print("Contoh 10 baris pertama:")
df.head(10)

Proses selesai ✔️
File disimpan sebagai: /content/drive/MyDrive/Rekap gangguan 4.csv
Contoh 10 baris pertama:

,Tgl KA,No KA,Id Penyebab,Nama_Penyebab,Id Akibat,Lokasi,Lokasi.1,Andil,Keterangan,source_file
0,2025-06-24,331,D1110,Gangguan Sistem Komputer,AT11,Lemahabang,Cikarang,13,imbas gangguan lok ka 2522,NaN
1,2025-06-24,332,D1110,Gangguan Sistem Komputer,AT11,-,Lemahabang,15,Gangguan lok KA 2522,NaN
2,2025-08-21,28,C3121,Imbas Faktor Gangguan Persinyalan Elektrik (Pe...,AT32,-,Gambir,18,ttunggu rangkaian dari ka 27 dat lambat imbas ...,NaN
3,2025-08-21,116,C3121,Imbas Faktor Gangguan Persinyalan Elektrik (Pe...,AT32,-,Jatinegara,5,antrian ka dengan ka 28 ber lambat imbas tungg...,NaN
4,2025-08-04,166,C1118,Gangguan Rel patah,AL10,-,Kosambi,54,imbas rel patah w.11b empl kos,NaN
5,2025-08-04,2,C1118,Gangguan Rel patah,AL10,-,Kosambi,28,imbas rel patah w.11b empl kos,NaN
6,2025-08-04,128,C1118,Gangguan Rel patah,AL10,-,Kosambi,44,imbas rel patah w.11b empl kos,NaN
7,2025-08-04,16,C1118,Gangguan Rel patah,AL10,-,Kosambi,41,imbas rel patah w.11b empl kos,NaN
8,2025-08-04,282,C1118,Gangguan Rel patah,AL10,-,Kosambi,24,imbas rel patah w.11b empl kos,NaN
9,2025-08-04,118,C1118,Gangguan Rel patah,AL10,-,Kosambi,29,imbas rel patah w.11b empl kos,NaN

In [ ]:
import pandas as pd

# Baca file hasil sebelumnya
path_rekap = "/content/drive/MyDrive/Rekap gangguan 4.csv"
df = pd.read_csv(path_rekap)

# Cek jumlah cell kosong
jumlah_kosong = df["Nama_Penyebab"].isna().sum()
print(f"Jumlah cell kosong pada kolom Nama_Penyebab: {jumlah_kosong}")

# Jika ada, tampilkan baris yang kosong
if jumlah_kosong > 0:
    print("\nBaris dengan Nama_Penyebab kosong:")
    display(df[df["Nama_Penyebab"].isna()].head(20))  # tampilkan 20 baris pertama
else:
    print("\nSemua cell pada kolom Nama_Penyebab terisi ✔️")

Jumlah cell kosong pada kolom Nama_Penyebab: 0

Semua cell pada kolom Nama_Penyebab terisi ✔️

In [ ]:
import pandas as pd

# Baca file terakhir
path_rekap = "/content/drive/MyDrive/Rekap gangguan 4.csv"
df = pd.read_csv(path_rekap)

# Tampilkan nilai unik kolom lokasi
print("=== Nilai unik pada kolom 'Lokasi' ===")
print(df['Lokasi'].unique())
print("\nJumlah nilai unik:", df['Lokasi'].nunique())

print("\n\n=== Nilai unik pada kolom 'Lokasi.1' ===")
print(df['Lokasi.1'].unique())
print("\nJumlah nilai unik:", df['Lokasi.1'].nunique())

=== Nilai unik pada kolom 'Lokasi' ===
['Lemahabang' '-' 'Kosambi' 'Gondangdia' 'Matraman' 'Gangsentiong'
 'Bekasi' 'Karawang' 'Cikini' 'Kedunggedeh' 'Cibitung' 'Bekasitimur'
 'Klari' 'Tambun' 'Dawuan' 'Jatinegara' 'Telaga Murni' 'Pondokjati'
 'Cikarang' 'Cikampek' 'Bogor Paledang' 'Pondok Leungsir' 'Manggarai'
 'Kramat' 'Rajawali' 'Ancol' 'Kemayoran' 'Sukabumi' 'Karangtengah'
 'Cibadak' 'Cijambe' 'Cigombong' 'Ciomas' 'Batutulis']

Jumlah nilai unik: 34


=== Nilai unik pada kolom 'Lokasi.1' ===
['Cikarang' 'Lemahabang' 'Gambir' 'Jatinegara' 'Kosambi' 'Karawang'
 'Klari' 'Pasarsenen' 'Cikampek' 'Kedunggedeh' 'Bekasi' 'Gondangdia'
 'Tambun' 'Bekasitimur' 'Dawuan' 'Manggarai' 'Matraman' 'Gangsentiong'
 'Cibitung' 'Pondokjati' 'Telaga Murni' 'Sukabumi' 'Bogor' 'Krenceng'
 'Parungkuda' 'Cisaat' 'Cikini' 'Kramat' 'Kampungbandan' 'Tanjungpriuk'
 'Ancol' 'Cibadak' 'Cicurug' 'Maseng' 'Batutulis' 'Bogor Paledang']

Jumlah nilai unik: 36

In [ ]:
import pandas as pd
import numpy as np

# 1. Baca file terakhir
path_rekap = "/content/drive/MyDrive/Rekap gangguan 4.csv"
df = pd.read_csv(path_rekap)

# 2. Deteksi mana yang terisi di kolom lokasi dan lokasi.1
#    Di sini: '-' juga dianggap KOSONG
lokasi_str = df['Lokasi'].astype(str).str.strip()
lokasi1_str = df['Lokasi.1'].astype(str).str.strip()

lokasi_filled = lokasi_str.ne('') & lokasi_str.ne('-') & df['Lokasi'].notna()
lokasi1_filled = lokasi1_str.ne('') & lokasi1_str.ne('-') & df['Lokasi.1'].notna()

# 3. Buat kolom jenis lokasi berdasarkan aturan:
#    - hanya satu yang terisi  -> "stasiun"
#    - dua-duanya terisi      -> "petak jalan"
#    - dua-duanya kosong      -> kosong ("")
df['jenis lokasi'] = np.select(
    [
        lokasi_filled ^ lokasi1_filled,   # XOR: hanya satu yang terisi
        lokasi_filled & lokasi1_filled    # keduanya terisi
    ],
    [
        'stasiun',
        'petak jalan'
    ],
    default=''
)

# 4. Posisikan kolom 'jenis lokasi' di sebelah kanan 'lokasi.1'
cols = list(df.columns)
idx = cols.index('Lokasi.1')
cols.insert(idx + 1, cols.pop(cols.index('jenis lokasi')))
df = df[cols]

# 5. Simpan sebagai file baru
output_path = "/content/drive/MyDrive/Rekap gangguan 5.csv"
df.to_csv(output_path, index=False)

print("Proses selesai ✔️")
print(f"File disimpan sebagai: {output_path}")
print("Contoh 10 baris pertama:")
df.head(10)

Proses selesai ✔️
File disimpan sebagai: /content/drive/MyDrive/Rekap gangguan 5.csv
Contoh 10 baris pertama:

,Tgl KA,No KA,Id Penyebab,Nama_Penyebab,Id Akibat,Lokasi,Lokasi.1,jenis lokasi,Andil,Keterangan,source_file
0,2025-06-24,331,D1110,Gangguan Sistem Komputer,AT11,Lemahabang,Cikarang,petak jalan,13,imbas gangguan lok ka 2522,NaN
1,2025-06-24,332,D1110,Gangguan Sistem Komputer,AT11,-,Lemahabang,stasiun,15,Gangguan lok KA 2522,NaN
2,2025-08-21,28,C3121,Imbas Faktor Gangguan Persinyalan Elektrik (Pe...,AT32,-,Gambir,stasiun,18,ttunggu rangkaian dari ka 27 dat lambat imbas ...,NaN
3,2025-08-21,116,C3121,Imbas Faktor Gangguan Persinyalan Elektrik (Pe...,AT32,-,Jatinegara,stasiun,5,antrian ka dengan ka 28 ber lambat imbas tungg...,NaN
4,2025-08-04,166,C1118,Gangguan Rel patah,AL10,-,Kosambi,stasiun,54,imbas rel patah w.11b empl kos,NaN
5,2025-08-04,2,C1118,Gangguan Rel patah,AL10,-,Kosambi,stasiun,28,imbas rel patah w.11b empl kos,NaN
6,2025-08-04,128,C1118,Gangguan Rel patah,AL10,-,Kosambi,stasiun,44,imbas rel patah w.11b empl kos,NaN
7,2025-08-04,16,C1118,Gangguan Rel patah,AL10,-,Kosambi,stasiun,41,imbas rel patah w.11b empl kos,NaN
8,2025-08-04,282,C1118,Gangguan Rel patah,AL10,-,Kosambi,stasiun,24,imbas rel patah w.11b empl kos,NaN
9,2025-08-04,118,C1118,Gangguan Rel patah,AL10,-,Kosambi,stasiun,29,imbas rel patah w.11b empl kos,NaN

In [ ]:
import pandas as pd

# 1. Baca file
path_rekap = "/content/drive/MyDrive/Rekap gangguan 5.csv"
df = pd.read_csv(path_rekap)

# --- 2. Rename kolom supaya L besar ---
df = df.rename(columns={
    'lokasi': 'Lokasi',
    'lokasi.1': 'Lokasi.1'
})

# 3. Normalisasi kolom Lokasi & Lokasi.1
lokasi = df['Lokasi'].astype(str).str.strip()
lokasi1 = df['Lokasi.1'].astype(str).str.strip()

# Anggap "-" dan "" sebagai kosong
lokasi = lokasi.replace(['-', ''], '')
lokasi1 = lokasi1.replace(['-', ''], '')

# 4. Buat kolom Lokasi (gabungan)
def merge_lokasi(a, b):
    if a and b:
        return f"{a} I {b}"
    elif a and not b:
        return a
    elif b and not a:
        return b
    else:
        return ""

df['Lokasi'] = [merge_lokasi(a, b) for a, b in zip(lokasi, lokasi1)]

# 5. Hapus kolom lama Lokasi.1
df = df.drop(columns=['Lokasi.1'])

# 6. Hapus kolom source_file bila ada
if 'source_file' in df.columns:
    df = df.drop(columns=['source_file'])

# 7. Simpan file baru
output_path = "/content/drive/MyDrive/Rekap gangguan 6.csv"
df.to_csv(output_path, index=False)

print("Proses selesai ✔️")
print(f"File disimpan sebagai: {output_path}")

# 8. Tampilkan 10 contoh
df[['Lokasi']].head(10)

Proses selesai ✔️
File disimpan sebagai: /content/drive/MyDrive/Rekap gangguan 6.csv

                  Lokasi
0  Lemahabang I Cikarang
1             Lemahabang
2                 Gambir
3             Jatinegara
4                Kosambi
5                Kosambi
6                Kosambi
7                Kosambi
8                Kosambi
9                Kosambi

In [ ]:
import pandas as pd

# Baca file terakhir
path_rekap = "/content/drive/MyDrive/Rekap gangguan 6.csv"
df = pd.read_csv(path_rekap)

# Hitung jumlah baris
jumlah_baris = len(df)

print(f"Jumlah baris dalam file: {jumlah_baris}")

Jumlah baris dalam file: 187342

In [ ]:
import pandas as pd

# 1. Baca file Rekap gangguan 6
rekap_path = "/content/drive/MyDrive/Rekap gangguan 6.csv"
df = pd.read_csv(rekap_path)

# 2. Baca file Nama KA.csv
nama_path = "/content/drive/MyDrive/Nama KA.csv"
df_nama = pd.read_csv(nama_path)

print("Kolom di Nama KA.csv:", df_nama.columns.tolist())

# 3. Tentukan nama kolom untuk Nomor KA dan Nama_KA (handle variasi nama)
# ---- Nomor KA
if "Nomor KA" in df_nama.columns:
    kol_nomor = "Nomor KA"
elif "No_KA" in df_nama.columns:
    kol_nomor = "No_KA"
else:
    raise ValueError("Tidak ditemukan kolom 'Nomor KA' atau 'No_KA' di file Nama KA.csv")

# ---- Nama KA
if "Nama_KA" in df_nama.columns:
    kol_nama = "Nama_KA"
elif "Nama KA" in df_nama.columns:
    kol_nama = "Nama KA"
else:
    raise ValueError("Tidak ditemukan kolom 'Nama_KA' atau 'Nama KA' di file Nama KA.csv")

# 4. Samakan format nomor KA (string + trim spasi)
df['No KA_clean'] = df['No KA'].astype(str).str.strip()
df_nama['Nomor KA_clean'] = df_nama[kol_nomor].astype(str).str.strip()

# 5. Buat df_nama unik per Nomor KA
df_nama_unique = df_nama.drop_duplicates(subset='Nomor KA_clean', keep='first')

# 6. Buat mapping: Nomor KA → Nama KA
mapping = df_nama_unique.set_index("Nomor KA_clean")[kol_nama]

# 7. Tambahkan kolom Nama_KA di Rekap gangguan 6
df["Nama_KA"] = df["No KA_clean"].map(mapping)

# 8. Letakkan Nama_KA di sebelah kanan kolom "No KA"
cols = list(df.columns)
idx = cols.index("No KA")
cols.insert(idx + 1, cols.pop(cols.index("Nama_KA")))
df = df[cols]

# 9. Hapus kolom helper
df = df.drop(columns=["No KA_clean"])

# 10. Simpan sebagai Rekap gangguan 7.csv
output_path = "/content/drive/MyDrive/Rekap gangguan 7.csv"
df.to_csv(output_path, index=False)

print("Proses selesai ✔️")
print(f"File disimpan sebagai: {output_path}")
df.head(10)

Kolom di Nama KA.csv: ['#', 'Nomor KA', 'Nama KA', 'Frekuensi', 'Lambat Awal (Menit)', 'Lambat Akhir (Menit)', 'Lambat Awal (Menit).1', 'Lambat Akhir (Menit).1', 'Rincian']
Proses selesai ✔️
File disimpan sebagai: /content/drive/MyDrive/Rekap gangguan 7.csv

,Tgl KA,No KA,Nama_KA,Id Penyebab,Nama_Penyebab,Id Akibat,Lokasi,jenis lokasi,Andil,Keterangan
0,2025-06-24,331,Commuter Line Walahar,D1110,Gangguan Sistem Komputer,AT11,Lemahabang I Cikarang,petak jalan,13,imbas gangguan lok ka 2522
1,2025-06-24,332,Commuter Line Walahar,D1110,Gangguan Sistem Komputer,AT11,Lemahabang,stasiun,15,Gangguan lok KA 2522
2,2025-08-21,28,Argo Merbabu,C3121,Imbas Faktor Gangguan Persinyalan Elektrik (Pe...,AT32,Gambir,stasiun,18,ttunggu rangkaian dari ka 27 dat lambat imbas ...
3,2025-08-21,116,Sawunggalih,C3121,Imbas Faktor Gangguan Persinyalan Elektrik (Pe...,AT32,Jatinegara,stasiun,5,antrian ka dengan ka 28 ber lambat imbas tungg...
4,2025-08-04,166,Dharmawangsa Ekspres,C1118,Gangguan Rel patah,AL10,Kosambi,stasiun,54,imbas rel patah w.11b empl kos
5,2025-08-04,2,Argo Bromo Anggrek,C1118,Gangguan Rel patah,AL10,Kosambi,stasiun,28,imbas rel patah w.11b empl kos
6,2025-08-04,128,Pangandaran,C1118,Gangguan Rel patah,AL10,Kosambi,stasiun,44,imbas rel patah w.11b empl kos
7,2025-08-04,16,Argo Dwipangga,C1118,Gangguan Rel patah,AL10,Kosambi,stasiun,41,imbas rel patah w.11b empl kos
8,2025-08-04,282,Bengawan,C1118,Gangguan Rel patah,AL10,Kosambi,stasiun,24,imbas rel patah w.11b empl kos
9,2025-08-04,118,Gunungjati,C1118,Gangguan Rel patah,AL10,Kosambi,stasiun,29,imbas rel patah w.11b empl kos

In [ ]:
df[df['Nama_KA'].isna()][['No KA']].drop_duplicates().head(20)

Empty DataFrame
Columns: [No KA]
Index: []